import { Module } from '@nestjs/common'
import { PrismaModule } from './prisma/prisma.module'
import { AuthModule } from './auth/auth.module'
import { AuditModule } from './audit/audit.module'
import { LiveModule } from './live/live.module'
import { PlatformModule } from './platform/platform.module'
import { RoleRequestsModule } from './role-requests/role-requests.module'
import { LinksModule } from './links/links.module'
import { ClassesModule } from './classes/classes.module'
import { UsersModule } from './users/users.module'
import { EventsModule } from './events/events.module'
import { AnnouncementsModule } from './announcements/announcements.module'
import { AttendanceModule } from './attendance/attendance.module'
import { NotificationsModule } from './notifications/notifications.module'
import { HomeworkModule } from './homework/homework.module'
import { TimetableModule } from './timetable/timetable.module'
import { ChatModule } from './chat/chat.module'
import { ExamsModule } from './exams/exams.module'
import { VoiceModule } from './voice/voice.module'
import { MessagesModule } from './messages/messages.module'
import { AdmissionsModule } from './admissions/admissions.module'
import { StudentsModule } from './students/students.module'
import { FeesModule } from './fees/fees.module'
import { DocumentsModule } from './documents/documents.module'
import { BillingModule } from './billing/billing.module'
import { SchoolDataModule } from './school-data/school-data.module'
import { AcademicModule } from './academic/academic.module'
import { CamerasModule } from './cameras/cameras.module'
import { McpModule } from './mcp/mcp.module'
import { ResourcesModule } from './resources/resources.module'
import { BooksModule } from './books/books.module'
import { IdCardsModule } from './idcards/idcards.module'
import { CertificatesModule } from './certificates/certificates.module'
import { LeaveModule } from './leave/leave.module'
import { InsightsModule } from './insights/insights.module'
import { StorageModule } from './storage/storage.module'
import { DriveModule } from './storage/drive.module'
import { ImportModule } from './import/import.module'

@Module({
  imports: [PrismaModule, EventsModule, LiveModule, AuditModule, StorageModule, ImportModule, PlatformModule, AuthModule, RoleRequestsModule, LinksModule, ClassesModule, UsersModule, AnnouncementsModule, AttendanceModule, NotificationsModule, HomeworkModule, TimetableModule, ChatModule, ExamsModule, VoiceModule, MessagesModule, AdmissionsModule, StudentsModule, FeesModule, CertificatesModule, IdCardsModule, ResourcesModule, BooksModule, AcademicModule, BillingModule, SchoolDataModule, DocumentsModule, LeaveModule, InsightsModule, CamerasModule, DriveModule, McpModule],
})
export class AppModule {}
